/**
  * Represents a granular text chunk derived from a parent document.
  */
export interface DocumentChunk {
  /** Unique identifier for the chunk. */
  id: string;
  /** Identifier linking back to the parent document or parent section. */
  parentId: string;
  /** The text content contained within this chunk. */
  content: string;
  /** Vector embedding representation of the chunk text. */
  embedding?: number[];
  /** Custom domain metadata attributes (e.g. section title, page number, author). */
  metadata: Record<string, unknown>;
}

/**
 * Represents a full domain document ingested into the RAG KnowledgeBase.
 */
export interface Document {
  /** Unique identifier for the document. */
  id: string;
  /** Title or filename of the document. */
  title: string;
  /** Raw un-chunked content of the full document. */
  rawContent: string;
  /** Granular chunks generated by a DocumentSplitter. */
  chunks: DocumentChunk[];
  /** Custom domain metadata bag. */
  metadata: Record<string, unknown>;
  /** Timestamp when the document was added or updated. */
  timestamp?: Date;
}

/**
 * Interface for splitting documents into chunks.
 */
export interface DocumentSplitter {
  /**
   * Splits a raw document into a collection of DocumentChunks.
   *
   * @param document The target Document to split.
   * @returns A promise resolving to an array of DocumentChunk objects.
   */
  splitDocument(document: Document): Promise<DocumentChunk[]>;
}
