import type { DocumentChunk } from './document.interface';

/**
 * Mutable execution context passed through the RAG Strategy Pipeline.
 */
export interface RAGContext {
  /** The initial raw query input provided by the user or agent. */
  query: string;

  /** Sub-queries or expanded search variations generated by QueryExpansionStrategy. */
  expandedQueries?: string[];

  /** Document chunks retrieved or candidate list being processed. */
  chunks?: DocumentChunk[];

  /** Numerical relevance scores associated with chunk IDs. */
  scores?: Map<string, number>;

  /** Hydrated parent context or full document content. */
  hydratedParentContext?: string;

  /** Compressed or pruned context text ready for insertion into the LLM prompt. */
  compressedContext?: string;

  /** Relational graph facts extracted by GraphRAGStrategy. */
  relationalFacts?: string[];

  /** Additional graph context details. */
  graphContext?: string;

  /** Hierarchical tree structure context. */
  hierarchicalTree?: unknown;

  /** Filter metadata for multi-tenant isolation or tags. */
  filter?: Record<string, unknown>;

  /** Custom strategy state metadata bag. */
  metadata?: Record<string, unknown>;
}

/**
 * Interface defining a modular strategy executed in pre-retrieval or post-retrieval RAG pipelines.
 */
export interface RAGStrategy {
  /** Unique name of the RAG strategy. */
  name: string;

  /**
   * Processes the strategy logic to mutate or enhance the RAGContext payload.
   * @param context RAG evaluation context object.
   * @returns Promise resolving to the updated RAGContext object.
   */
  process(context: RAGContext): Promise<RAGContext> | RAGContext;
}
