import type { DocumentChunk } from './document.interface';

/**
 * Mutable execution context passed through the RAG Strategy Pipeline.
 */
export interface RAGContext {
  /** The initial raw query input provided by the user or agent. */
  query: string;
  /** Sub-queries or expanded search variations generated by QueryExpansionStrategy. */
  expandedQueries?: string[];
  /** Document chunks retrieved or candidate list being processed. */
  chunks?: DocumentChunk[];
  /** Numerical relevance scores associated with chunk IDs. */
  scores?: Map<string, number>;
  /** Hydrated parent context or full document content. */
  hydratedParentContext?: string;
  /** Compressed or pruned context text ready for insertion into the LLM prompt. */
  compressedContext?: string;
  /** Hierarchical tree representations generated by HierarchicalRAGStrategy. */
  hierarchicalTree?: Record<string, unknown>[];
  /** Relational Knowledge Graph facts generated by GraphRAGStrategy. */
  graphContext?: string;
  /** Additional domain metadata attributes bag. */
  metadata?: Record<string, unknown>;
}

/**
 * Modular RAG Strategy interface.
 * Implemented by QueryExpansionStrategy, HierarchicalRAGStrategy, LateChunkingStrategy,
 * ParentChildHydrationStrategy, ContextualCompressionStrategy, and RerankerStrategy.
 */
export interface RAGStrategy {
  /** Descriptive name of the strategy (e.g. "QueryExpansion", "ParentChildHydration"). */
  readonly name: string;

  /**
   * Processes and enhances the RAG context within the pipeline.
   *
   * @param context The current RAGContext state.
   * @returns A promise resolving to the modified/enhanced RAGContext.
   */
  process(context: RAGContext): Promise<RAGContext>;
}
