import type { AgentRunner } from '@nestjs-agentic/core';
import type { ParallelRunnerOptions, SubAgentResult, SubAgentTask } from '../interfaces/orchestration.interface';
import { ParentSecurityContext, SubAgentDelegator } from '../delegator/sub-agent.delegator';

/**
 * Result payload returned from a parallel sub-agent fan-out execution run.
 */
export interface ParallelRunResult {
  /** Combined text response output generated by aggregating all sub-agent results. */
  combinedResponse: string;

  /** List of individual sub-agent execution results. */
  results: SubAgentResult[];

  /** Total number of sub-agents that executed successfully. */
  successCount: number;

  /** Total number of sub-agents that failed or timed out. */
  failedCount: number;
}

/**
 * Runner service for executing multiple sub-agents in parallel with retries, fallback recovery, and score-weighted consensus.
 */
export class ParallelSubAgentRunner {
  private readonly delegator: SubAgentDelegator;
  private readonly options: ParallelRunnerOptions;

  /**
   * Creates a new instance of ParallelSubAgentRunner.
   * @param runner Core AgentRunner instance.
   * @param options Configuration options for parallel execution.
   */
  constructor(runner: AgentRunner, options?: ParallelRunnerOptions) {
    this.delegator = new SubAgentDelegator(runner);
    this.options = {
      aggregationStrategy: options?.aggregationStrategy ?? 'allSettled',
      timeoutMs: options?.timeoutMs ?? 30000,
      retriesPerSubAgent: options?.retriesPerSubAgent ?? 1,
      maxConcurrency: options?.maxConcurrency,
      signal: options?.signal,
      fallbackAgentName: options?.fallbackAgentName,
      customMergerFn: options?.customMergerFn,
    };
  }

  /**
   * Executes multiple sub-agents in parallel and aggregates their responses based on the configured aggregation strategy.
   *
   * @param parentSessionId The parent session identifier.
   * @param parentSecurityContext Inherited parent security context.
   * @param tasks Array of sub-agent task definitions to run concurrently.
   * @returns Promise resolving to the combined parallel execution result.
   */
  async runParallel(
    parentSessionId: string,
    parentSecurityContext: ParentSecurityContext,
    tasks: SubAgentTask[],
  ): Promise<ParallelRunResult> {
    if (!tasks || tasks.length === 0) {
      return { combinedResponse: '', results: [], successCount: 0, failedCount: 0 };
    }

    if (this.options.signal?.aborted) {
      const abortedResults: SubAgentResult[] = tasks.map((t) => ({
        agentName: t.agentName,
        status: 'failed',
        response: '',
        toolCount: 0,
        error: 'Parallel execution was aborted',
      }));
      return {
        combinedResponse: 'Parallel execution was aborted',
        results: abortedResults,
        successCount: 0,
        failedCount: tasks.length,
      };
    }

    const executeTaskWithRetryAndFallback = async (task: SubAgentTask): Promise<SubAgentResult> => {
      const activeSignal = task.signal ?? this.options.signal;
      if (activeSignal?.aborted) {
        return {
          agentName: task.agentName,
          status: 'failed',
          response: '',
          toolCount: 0,
          error: 'Sub-agent run was aborted',
        };
      }

      let attempts = 0;
      let lastResult: SubAgentResult | null = null;
      const maxAttempts = (this.options.retriesPerSubAgent ?? 1) + 1;

      while (attempts < maxAttempts) {
        if (activeSignal?.aborted) {
          return {
            agentName: task.agentName,
            status: 'failed',
            response: '',
            toolCount: 0,
            error: 'Sub-agent run was aborted',
          };
        }

        attempts++;

        let timer: NodeJS.Timeout | undefined;
        let abortHandler: (() => void) | undefined;

        const timeoutPromise = new Promise<SubAgentResult>((resolve) => {
          timer = setTimeout(() => {
            resolve({
              agentName: task.agentName,
              status: 'failed',
              response: '',
              toolCount: 0,
              error: `Sub-agent ${task.agentName} timed out after ${this.options.timeoutMs}ms`,
            });
          }, this.options.timeoutMs);
        });

        const abortPromise = new Promise<SubAgentResult>((resolve) => {
          if (activeSignal?.aborted) {
            resolve({
              agentName: task.agentName,
              status: 'failed',
              response: '',
              toolCount: 0,
              error: 'Sub-agent run was aborted',
            });
            return;
          }
          if (activeSignal) {
            abortHandler = () => {
              resolve({
                agentName: task.agentName,
                status: 'failed',
                response: '',
                toolCount: 0,
                error: 'Sub-agent run was aborted',
              });
            };
            activeSignal.addEventListener('abort', abortHandler, { once: true });
          }
        });

        try {
          lastResult = await Promise.race([
            this.delegator.delegate(parentSessionId, parentSecurityContext, task, undefined, activeSignal),
            timeoutPromise,
            abortPromise,
          ]);
        } finally {
          if (timer) clearTimeout(timer);
          if (activeSignal && abortHandler) {
            activeSignal.removeEventListener('abort', abortHandler);
          }
        }

        if (lastResult.status === 'success' || activeSignal?.aborted) {
          return lastResult;
        }
      }

      // Fallback agent execution if primary sub-agent fails all retries and is not aborted
      if (!activeSignal?.aborted && this.options.fallbackAgentName && this.options.fallbackAgentName !== task.agentName) {
        const fallbackTask: SubAgentTask = {
          ...task,
          agentName: this.options.fallbackAgentName,
        };

        let fallbackTimer: NodeJS.Timeout | undefined;
        let fallbackAbortHandler: (() => void) | undefined;

        const fallbackTimeoutPromise = new Promise<SubAgentResult>((resolve) => {
          fallbackTimer = setTimeout(() => {
            resolve({
              agentName: this.options.fallbackAgentName!,
              status: 'failed',
              response: '',
              toolCount: 0,
              error: `Fallback sub-agent ${this.options.fallbackAgentName} timed out after ${this.options.timeoutMs}ms`,
            });
          }, this.options.timeoutMs);
        });

        const fallbackAbortPromise = new Promise<SubAgentResult>((resolve) => {
          if (activeSignal?.aborted) {
            resolve({
              agentName: this.options.fallbackAgentName!,
              status: 'failed',
              response: '',
              toolCount: 0,
              error: 'Sub-agent run was aborted',
            });
            return;
          }
          if (activeSignal) {
            fallbackAbortHandler = () => {
              resolve({
                agentName: this.options.fallbackAgentName!,
                status: 'failed',
                response: '',
                toolCount: 0,
                error: 'Sub-agent run was aborted',
              });
            };
            activeSignal.addEventListener('abort', fallbackAbortHandler, { once: true });
          }
        });

        try {
          const fallbackResult = await Promise.race([
            this.delegator.delegate(
              parentSessionId,
              parentSecurityContext,
              fallbackTask,
              undefined,
              activeSignal,
            ),
            fallbackTimeoutPromise,
            fallbackAbortPromise,
          ]);

          if (fallbackResult.status === 'success') {
            return {
              ...fallbackResult,
              response: `[Fallback Agent ${this.options.fallbackAgentName}]: ${fallbackResult.response}`,
            };
          }
          lastResult = fallbackResult;
        } finally {
          if (fallbackTimer) clearTimeout(fallbackTimer);
          if (activeSignal && fallbackAbortHandler) {
            activeSignal.removeEventListener('abort', fallbackAbortHandler);
          }
        }
      }

      return lastResult!;
    };

    const results = await mapConcurrent(
      tasks,
      this.options.maxConcurrency,
      this.options.signal,
      (t) => executeTaskWithRetryAndFallback(t),
    );
    const successCount = results.filter((r) => r.status === 'success').length;
    const failedCount = results.length - successCount;

    let combinedResponse = '';

    if (this.options.customMergerFn) {
      combinedResponse = await this.options.customMergerFn(results);
    } else if (this.options.aggregationStrategy === 'firstSuccess') {
      const first = results.find((r) => r.status === 'success');
      combinedResponse = first?.response || '';
    } else if (this.options.aggregationStrategy === 'consensusMerge') {
      const validResults = results.filter((r) => r.status === 'success');
      if (validResults.length === 0) {
        combinedResponse = 'All sub-agents failed to return valid results.';
      } else {
        validResults.sort((a, b) => (b.score || 0) - (a.score || 0));
        combinedResponse = validResults.map((r) => `[${r.agentName}]: ${r.response}`).join('\n\n');
      }
    } else {
      combinedResponse = results
        .map((r) => {
          if (r.status === 'success') {
            return `[${r.agentName} SUCCESS]: ${r.response}`;
          }
          return `[${r.agentName} FAILED]: ${r.error}`;
        })
        .join('\n\n');
    }

    return {
      combinedResponse,
      results,
      successCount,
      failedCount,
    };
  }
}

/**
 * Runs tasks with a maximum concurrency limit and cancellation awareness.
 */
async function mapConcurrent<T, R>(
  items: T[],
  concurrency: number | undefined,
  signal: AbortSignal | undefined,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  if (!concurrency || concurrency >= items.length || concurrency < 1) {
    return Promise.all(items.map(fn));
  }

  const results: R[] = new Array(items.length);
  let currentIndex = 0;

  const workers = Array.from({ length: concurrency }, async () => {
    while (currentIndex < items.length) {
      if (signal?.aborted) {
        break;
      }
      const index = currentIndex++;
      results[index] = await fn(items[index]);
    }
  });

  await Promise.all(workers);

  // Fill in any unstarted tasks due to abort
  for (let i = 0; i < items.length; i++) {
    if (results[i] === undefined) {
      results[i] = (await fn(items[i])) as R;
    }
  }

  return results;
}

