import type { AgentContext, ExecutionLimits } from '@nestjs-agentic/core';

/**
 * Capability narrowing constraints applied when delegating work to a subordinate agent.
 * Enforces the Principle of Least Privilege across sub-agent executions.
 */
export interface CapabilityNarrowing {
  /** Whitelist of tool names the sub-agent is permitted to call. */
  allowedTools?: string[];

  /** Blacklist of tool names the sub-agent is prohibited from calling. */
  deniedTools?: string[];

  /** Narrowed permission scopes (subset of parent permissions). */
  allowedPermissions?: string[];

  /** Narrowed roles (subset of parent roles). */
  allowedRoles?: string[];

  /** Sub-agent execution limits (iteration budgets, token bounds, timeout). */
  limits?: ExecutionLimits;
}

/**
 * Internal namespaced context metadata stored under `context.data.agentic`.
 */
export interface AgenticInternalContext {
  /** Capability narrowing rules active for the current agent turn. */
  capabilityNarrowing?: CapabilityNarrowing;

  /** Current sub-agent delegation depth in the execution tree. */
  delegationDepth?: number;
}

/**
 * Task payload for delegating work to a designated sub-agent.
 */
export interface SubAgentTask {
  /** Target registered sub-agent name. */
  agentName: string;

  /** Input message or instruction prompt string for the sub-agent. */
  message: string;

  /** Capability narrowing constraints applied to this sub-agent run. */
  narrowing?: CapabilityNarrowing;

  /** Custom metadata key-value pairs passed in context.data. */
  data?: Record<string, unknown>;

  /** Optional AbortSignal to cancel this sub-agent execution. */
  signal?: AbortSignal;
}

/**
 * Execution result output returned from a sub-agent execution.
 */
export interface SubAgentResult {
  /** Name of the target sub-agent. */
  agentName: string;

  /** Execution status of the sub-agent run. */
  status: 'success' | 'failed' | 'denied';

  /** Primary text response output generated by the sub-agent. */
  response: string;

  /** Total number of tool calls executed during the sub-agent run. */
  toolCount: number;

  /** Detailed error message string if the sub-agent execution failed. */
  error?: string;

  /** Optional numerical confidence or quality evaluation score (0.0 to 1.0). */
  score?: number;
}

/**
 * Strategy for aggregating parallel sub-agent execution results.
 */
export type AggregationStrategy = 'allSettled' | 'firstSuccess' | 'consensusMerge';

/**
 * Options for configuring parallel sub-agent fan-out execution.
 */
export interface ParallelRunnerOptions {
  /** Strategy for combining sub-agent responses. Default: `'allSettled'` */
  aggregationStrategy?: AggregationStrategy;

  /** Timeout per sub-agent execution in milliseconds. Default: `30000` */
  timeoutMs?: number;

  /** Number of retries per sub-agent upon timeout or execution failure. Default: `1` */
  retriesPerSubAgent?: number;

  /** Maximum number of sub-agents allowed to run concurrently. Default: unlimited */
  maxConcurrency?: number;

  /** Optional AbortSignal to cancel all running and queued sub-agents. */
  signal?: AbortSignal;

  /** Name of fallback sub-agent to invoke if primary sub-agent fails all retries. */
  fallbackAgentName?: string;

  /** Custom merger function to combine sub-agent results. */
  customMergerFn?: (results: SubAgentResult[]) => Promise<string> | string;
}

/**
 * Options for configuring supervisor-worker iterative refinement loops.
 */
export interface RefinementLoopOptions {
  /** Maximum number of loop iterations allowed. Default: `3` */
  maxIterations?: number;

  /** Target quality score threshold (0.0 to 1.0) to terminate the loop early. Default: `0.85` */
  qualityThreshold?: number;

  /** Optional AbortSignal to cancel the refinement loop. */
  signal?: AbortSignal;

  /** Custom satisfaction evaluator function to determine if the result meets loop termination criteria. */
  satisfactionFn?: (result: SubAgentResult, iteration: number) => Promise<boolean> | boolean;
}
