import type { AgentContext, ExecutionLimits, StateStore } from '@nestjs-agentic/core';

/**
 * Capability narrowing constraints applied when delegating work to a subordinate agent.
 * Enforces the Principle of Least Privilege across sub-agent executions.
 */
export interface CapabilityNarrowing {
  /** Whitelist of tool names the sub-agent is permitted to call. */
  allowedTools?: string[];

  /** Blacklist of tool names the sub-agent is prohibited from calling. */
  deniedTools?: string[];

  /** Narrowed permission scopes (subset of parent permissions). */
  allowedPermissions?: string[];

  /** Narrowed roles (subset of parent roles). */
  allowedRoles?: string[];

  /** Sub-agent execution limits (iteration budgets, token bounds, timeout). */
  limits?: ExecutionLimits;
}

/**
 * Internal namespaced context metadata stored under `context.data.agentic`.
 */
export interface AgenticInternalContext {
  /** Capability narrowing rules active for the current agent turn. */
  capabilityNarrowing?: CapabilityNarrowing;

  /** Current sub-agent delegation depth in the execution tree. */
  delegationDepth?: number;
}

/**
 * Task payload for delegating work to a designated sub-agent.
 */
export interface SubAgentTask {
  /** Target registered sub-agent name. */
  agentName: string;

  /** Input message or instruction prompt string for the sub-agent. */
  message: string;

  /** Capability narrowing constraints applied to this sub-agent run. */
  narrowing?: CapabilityNarrowing;

  /** Custom metadata key-value pairs passed in context.data. */
  data?: Record<string, unknown>;

  /** Optional AbortSignal to cancel this sub-agent execution. */
  signal?: AbortSignal;
}

/**
 * Execution result output returned from a sub-agent execution.
 */
export interface SubAgentResult {
  /** Name of the target sub-agent. */
  agentName: string;

  /** Execution status of the sub-agent run. */
  status: 'success' | 'failed' | 'denied';

  /** Primary text response output generated by the sub-agent. */
  response: string;

  /** Total number of tool calls executed during the sub-agent run. */
  toolCount: number;

  /** Detailed error message string if the sub-agent execution failed. */
  error?: string;

  /** Optional numerical confidence or quality evaluation score (0.0 to 1.0). */
  score?: number;

  /** Token consumption details during this sub-agent run. */
  tokens?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
  };

  /** Execution duration of this sub-agent run in milliseconds. */
  durationMs?: number;
}

/**
 * Cumulative token and execution duration budgets enforced across iterative refinement loops.
 */
export interface RefinementLoopBudget {
  /** Maximum cumulative tokens allowed across all iterations. */
  maxTotalTokens?: number;

  /** Maximum cumulative execution time in milliseconds across all iterations. */
  maxTotalTimeMs?: number;
}

/**
 * Structured result returned by a satisfaction evaluator in refinement loops.
 */
export interface SatisfactionResult {
  /** Whether the sub-agent output meets satisfaction criteria to terminate the loop. */
  satisfied: boolean;

  /** Optional evaluation confidence or quality score (0.0 to 1.0). */
  score?: number;

  /** Actionable feedback instruction prompt for the next iteration (if not satisfied). */
  feedback?: string;

  /** Detailed diagnostic or rationale string for the evaluation decision. */
  reason?: string;
}

/**
 * Checkpoint snapshot of an in-flight iterative refinement loop.
 */
export interface RefinementLoopCheckpoint {
  /** Checkpoint schema version. */
  version: 1;

  /** Monotonically increasing sequence number for optimistic concurrency. */
  checkpointSequence: number;

  /** Parent session identifier. */
  parentSessionId: string;

  /** Tenant identifier for multi-tenant isolation. */
  tenantId?: string;

  /** Target worker sub-agent name. */
  agentName: string;

  /** Last completed iteration index (1-based). */
  iteration: number;

  /** Maximum allowed iterations configured for the loop. */
  maxIterations: number;

  /** History of sub-agent results up to this iteration. */
  history: SubAgentResult[];

  /** Cumulative tokens consumed across iterations. */
  totalTokens: number;

  /** Cumulative execution duration across iterations in milliseconds. */
  totalDurationMs: number;

  /** Prompt message prepared for the next iteration. */
  currentMessage: string;

  /** Source indicating where the feedback for the next iteration originated. */
  feedbackSource: 'provider' | 'evaluator' | 'default';

  /** ISO timestamp when the checkpoint was saved. */
  savedAt: string;

  /** Custom state metadata dictionary. */
  metadata?: Record<string, unknown>;
}

/**
 * Strategy for aggregating parallel sub-agent execution results.
 *
 * - `allSettled`: Run all sub-agents, merge every result.
 * - `firstSuccess`: Race all sub-agents, cancel losers on first success.
 * - `bestOf`: Run all sub-agents, pick the best by evaluator or score.
 * - `consensusMerge`: Run all sub-agents, merge with convergence scoring.
 * - `fallbackChain`: Execute sub-agents sequentially until one succeeds.
 */
export type AggregationStrategy =
  | 'allSettled'
  | 'firstSuccess'
  | 'bestOf'
  | 'consensusMerge'
  | 'fallbackChain';

/**
 * Options for configuring parallel sub-agent fan-out execution.
 */
export interface ParallelRunnerOptions {
  /** Strategy for combining sub-agent responses. Default: `'allSettled'` */
  aggregationStrategy?: AggregationStrategy;

  /** Timeout per sub-agent execution in milliseconds. Default: `30000` */
  timeoutMs?: number;

  /** Number of retries per sub-agent upon timeout or execution failure. Default: `1` */
  retriesPerSubAgent?: number;

  /** Maximum number of sub-agents allowed to run concurrently. Default: unlimited */
  maxConcurrency?: number;

  /** Optional AbortSignal to cancel all running and queued sub-agents. */
  signal?: AbortSignal;

  /** Name of fallback sub-agent to invoke if primary sub-agent fails all retries. */
  fallbackAgentName?: string;

  /** Custom merger function to combine sub-agent results. */
  customMergerFn?: (results: SubAgentResult[]) => Promise<string> | string;

  /**
   * Custom evaluator function to select the best sub-agent result from successful executions.
   * Used by the `bestOf` aggregation strategy.
   *
   * @param results - Array of successful sub-agent execution results.
   * @returns The chosen winner SubAgentResult. If it throws or returns an invalid result,
   * the runner automatically falls back to highest score selection.
   */
  evaluatorFn?: (results: SubAgentResult[]) => Promise<SubAgentResult> | SubAgentResult;

  /**
   * Consensus convergence threshold (0.0 to 1.0) for multi-agent debate and consensus merging.
   * Default: `0.7`
   */
  consensusThreshold?: number;
}

/**
 * Options for configuring supervisor-worker iterative refinement loops.
 */
export interface RefinementLoopOptions {
  /** Maximum number of loop iterations allowed. Default: `3` */
  maxIterations?: number;

  /** Target quality score threshold (0.0 to 1.0) to terminate early. Default: `0.85` */
  qualityThreshold?: number;

  /** Optional AbortSignal to cancel the refinement loop. */
  signal?: AbortSignal;

  /** Cumulative token and duration budget guardrails across iterations. */
  budget?: RefinementLoopBudget;

  /** Optional persistence store for automatic loop checkpointing across iterations. */
  stateStore?: StateStore;

  /** Checkpoint TTL in seconds when saving to stateStore. Default: `86400` (24h). */
  checkpointTtlSeconds?: number;

  /** Checkpoint TTL in seconds when saving failed/aborted loop checkpoints. Default: `3600` (1h). */
  errorCheckpointTtlSeconds?: number;

  /** Lock TTL in seconds to prevent concurrent executions of the same loop. Default: `60` (1 min). */
  lockTtlSeconds?: number;

  /** Custom satisfaction evaluator returning boolean or structured SatisfactionResult. */
  satisfactionFn?: (
    result: SubAgentResult,
    iteration: number,
  ) => Promise<boolean | SatisfactionResult> | boolean | SatisfactionResult;
}

/**
 * Result payload returned from an iterative refinement loop run.
 */
export interface RefinementLoopResult {
  /** Final text response output generated upon loop termination. */
  finalResponse: string;

  /** Total number of refinement iterations executed. */
  iterations: number;

  /** Whether the loop satisfied the termination condition before maxIterations was reached. */
  satisfied: boolean;

  /** Chronological history of sub-agent results for each loop iteration. */
  history: SubAgentResult[];

  /** Specific reason why the refinement loop terminated. */
  terminationReason: 'satisfied' | 'max_iterations' | 'budget_exceeded' | 'aborted' | 'error';

  /** Cumulative tokens consumed across all loop iterations. */
  totalTokens: number;

  /** Cumulative execution duration across all loop iterations in milliseconds. */
  totalDurationMs: number;
}
