import type { ParentSecurityContext } from '../delegator/sub-agent.delegator';

export interface SubAgentTask {
  /** Target registered sub-agent name. */
  agentName: string;
  /** Input message string for the sub-agent. */
  message: string;
  /** Task-specific security context overrides or metadata. */
  context?: Partial<ParentSecurityContext>;
}

export interface SubAgentResult {
  /** Target sub-agent name. */
  agentName: string;
  /** Sub-agent execution status ('success' | 'failed' | 'denied'). */
  status: 'success' | 'failed' | 'denied';
  /** Primary string response or summary generated by the sub-agent. */
  response: string;
  /** Tool call count during sub-agent execution. */
  toolCount: number;
  /** Detailed error message if sub-agent failed. */
  error?: string;
  /** Optional numerical confidence/quality score (0.0 to 1.0). */
  score?: number;
}

export type AggregationStrategy = 'allSettled' | 'firstSuccess' | 'consensusMerge';

export interface ParallelRunnerOptions {
  /** Aggregation strategy for combining sub-agent results. Default: 'allSettled' */
  aggregationStrategy?: AggregationStrategy;
  /** Timeout per sub-agent in milliseconds. Default: 30000 */
  timeoutMs?: number;
  /** Number of retries per sub-agent upon timeout or failure. Default: 1 */
  retriesPerSubAgent?: number;
  /** Name of fallback sub-agent to invoke if primary sub-agent fails all retries. */
  fallbackAgentName?: string;
  /** Custom result merger function. */
  customMergerFn?: (results: SubAgentResult[]) => Promise<string> | string;
}

export interface RefinementLoopOptions {
  /** Maximum number of loop iterations. Default: 3 */
  maxIterations?: number;
  /** Target quality score threshold (0.0 to 1.0) to terminate early. Default: 0.85 */
  qualityThreshold?: number;
  /** Custom satisfaction evaluator function. */
  satisfactionFn?: (result: SubAgentResult, iteration: number) => Promise<boolean> | boolean;
}
